language: ruby
script: "bundle exec cucumber"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
env: TEST=true TRAVIS=true
gemfile:
  - Gemfile
notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/d75034d3-11f7-4e03-9abc-8d84f783a855

